### ISSUE TITLE
Adding the appsettings.json file

### ISSUE THREAD

**Issue by FabianGosebrink** [tedonmain/vs2017win#1]
After cloning this the appsettings.json file is missing. Can you add that?

**Comment by tedonmain** [comment]
OK added for both projects. I just thought you would use your own. thanks!

**Comment by tedonmain** [comment]
Turns out I sent this to myself. I didn’t see that I was replying to my GitHub email.

**Comment by FabianGosebrink** [comment]
Hey Ted, easy :) You did everything correct, I just did not look into this thread again. No worries :) If you have submitted the file and solved the changes, just commit that I can take a look. Thank you :)

**Comment by tedonmain** [comment]
committed changes. thanks!
